name: allsearch
services:
  allsearch_database:
    type: postgres:13
    portforward: true
  catalog_solr:
    type: solr:8.4
    portforward: true
    core: catalog
    config:
      dir: "solr/solr_configs/catalog-production-v2/conf"
  dpul_solr:
    type: solr:8.4
    portforward: true
    core: dpul
    config:
      dir: "solr/solr_configs/dpul/conf"
  findingaids_solr:
    type: solr:8.4
    portforward: true
    core: findingaids
    config:
      dir: "solr/solr_configs/pulfalight-production/conf"
  pulmap:
    type: solr:8.4
    portforward: true
    core: pulmap
    config: 
      dir: "solr/solr_configs/pulmap/conf"
proxy:
  catalog_solr:
    - catalog.dev.solr.lndo.site:8983
  dpul_solr:
    - dpul.dev.solr.lndo.site:8983
  findingaids_solr:
    - findingaids.dev.solr.lndo.site:8983
  pulmap:
    - pulmap.dev.solr.lndo.site:8983
