inherit_from: .rubocop_todo.yml
require: 
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'solr/**/*'
    - 'vendor/bundle/**/*'

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/requests/api/catalog_spec.rb'

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets
  MinSize: 8
