inherit_from: .rubocop_todo.yml
require: 
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/Documentation:
  Enabled: false
