version: 2.1
orbs:
  ruby: circleci/ruby@2.1.0
executors:
  allsearch-executor:
    docker:
      - image: cimg/ruby:3.3.0-browsers
        environment:
          RAILS_ENV: test
          ALLSEARCH_HOST: localhost
          AllSEARCH_USER: postgres
          SOLR_URL: http://solr:SolrRocks@localhost:8983/solr/allsearch-test
          COVERALLS_PARALLEL: true
      - image: cimg/postgres:15.4
        environment:
          POSTGRES_USER: allsearch
          POSTGRES_PASSWORD: allsearch
          POSTGRES_DB: allsearch_test
    working_directory: ~/allsearch_api  
commands:
  setup-bundler:
    steps:
      - run:
          name: Install bundler
          command: gem install bundler -v '2.4.19'
      # Restore bundle cache
      - restore_cache:
          keys:
          - allsearch-v1-{{ checksum "Gemfile.lock" }}
      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3
      - save_cache:
          key: allsearch-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
jobs:
  build:
    docker:
      - image: cimg/ruby:3.3
    steps:
      - checkout
      - ruby/install-deps
  checking:
    docker: 
      - image: cimg/ruby:3.3
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop
  reek:
    docker:
      - image: cimg/ruby:3.3
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Check code smells with Reek
          command: bundle exec reek app
  test:
    executor: allsearch-executor
    parallelism: 3
    steps:
      - attach_workspace:
          at: '~/allsearch_api'
      - checkout
      - setup-bundler
      - run: ruby --version
      - run: sudo apt install postgresql-client
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rake db:setup
      - ruby/install-deps
      - ruby/rspec-test:
          include: spec/**/*_spec.rb
  semgrep:
    docker:
        - image: returntocorp/semgrep
    steps:
      - checkout
      - run:
          name: Check code against community-provided and custom semgrep rules
          command: semgrep ci --config auto --config .semgrep.yml
  brakeman:
    executor: allsearch-executor
    steps:
      - attach_workspace:
          at: '~/allsearch_api'
      - checkout
      - setup-bundler
      - run: 
          name: Check code for vulnerabilities
          command: bundle exec brakeman
  vacuum:
    executor: allsearch-executor
    steps:
      - attach_workspace:
          at: '~/allsearch_api'
      - checkout
      - run:
          name: Install vacuum
          command: npm install -g @quobix/vacuum --prefix=$HOME/.local
      - run:
          name: Validate swagger yaml file againt OpenAPI standard
          command: vacuum lint -d swagger/**/*.yaml

workflows:
  build_and_test:
    jobs:
      - build
      - checking
      - reek
      - brakeman
      - test:
          requires:
            - build
      - semgrep
      - vacuum
