---
openapi: 3.0.1
info:
  title: Allsearch API
  version: v1
paths: {}
components:
  schemas:
    not_found:
      type: object
      properties:
        message:
          type: string
    service:
      type: object
      required:
      - query
      properties:
        query:
          type: string
          example: Hi there!
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
