---
openapi: 3.0.1
info:
  title: Allsearch API
  version: v1
paths:
  "/search/artmuseum?query={query}":
    parameters:
    - name: query
      in: path
      description: A string to query the Art Museum
      required: true
      schema:
        type: string
    get:
      summary: "/search/artmuseum?query={query}"
      tags:
      - Art Museum
      description: Searches the Art Museum using a query term
      responses:
        '200':
          description: successful
  "/search/best-bet?query={query}":
    parameters:
    - name: query
      in: path
      description: A string to query the Best-Bets
      required: true
      schema:
        type: string
    get:
      summary: "/search/best-bet?query={query}"
      tags:
      - Best Bets
      description: Searches the Best Bets using a query term
      responses:
        '200':
          description: successful
  "/search/catalog?query={query}":
    parameters:
    - name: query
      in: path
      description: A string to query the Catalog
      required: true
      schema:
        type: string
    get:
      summary: "/search/catalog?query={query}"
      tags:
      - Catalog
      description: Searches the Catalog using a query term
      responses:
        '200':
          description: successful
  "/search/dpul?query={query}":
    parameters:
    - name: query
      in: path
      description: A string to query Dpul
      required: true
      schema:
        type: string
    get:
      summary: "/search/dpul?query={query}"
      tags:
      - Dpul
      description: Searches Dpul using a query term
      responses:
        '200':
          description: successful
  "/search/findingaids?query={query}":
    parameters:
    - name: query
      in: path
      description: A string to query Findingaids
      required: true
      schema:
        type: string
    get:
      summary: "/search/findingaids?query={query}"
      tags:
      - Findingaids
      description: Searches Findingaids using a query term
      responses:
        '200':
          description: successful
  "/search/libguides?query={query}":
    parameters:
    - name: query
      in: path
      description: A string to query Libguides
      required: true
      schema:
        type: string
    get:
      summary: "/search/libguides?query={query}"
      tags:
      - Libguides
      description: Searches the Libguides research guides using a query term
      responses:
        '200':
          description: successful
  "/search/pulmap?query={query}":
    parameters:
    - name: query
      in: path
      description: A string to query Pulmap
      required: true
      schema:
        type: string
    get:
      summary: "/search/pulmap?query={query}"
      tags:
      - Pulmap
      description: Searches Pulmap using a query term
      responses:
        '200':
          description: successful
servers:
- url: "/"
