default: &default
  catalog:
    solr:
      host: "lib-solr8-prod.princeton.edu"
      port: 8983
      collection: "catalog-alma-production"
  dpul:
    solr:
      host: "lib-solr8-prod.princeton.edu"
      port: 8983
      collection: "dpul-production"
  findingaids:
    solr:
      host: "lib-solr8-prod.princeton.edu"
      port: 8983
      collection: "pulfalight-production"
  libanswers:
    client_id: <%= ENV['LIBANSWERS_CLIENT_ID'] || 'ABC' %>
    client_secret: <%= ENV['LIBANSWERS_CLIENT_SECRET'] || '12345' %>
  libguides:
    client_id: <%= ENV['LIBGUIDES_CLIENT_ID'] || 'ABC' %>
    client_secret: <%= ENV['LIBGUIDES_CLIENT_SECRET'] || '12345' %>
  pulmap:
    solr: 
      host: "lib-solr8-prod.princeton.edu"
      port: 8983
      collection: "pulmap"
  summon:
    access_id: 'princeton'
    api_host: 'api.summon.serialssolutions.com'
    api_path: '/2.0.0/search'
    secret_key: <%= ENV['SUMMON_SECRET_KEY'] || 'summon-secret-key' %>
development:
  <<: *default
  catalog:
    solr:
      host: <%= ENV["lando_catalog_solr_conn_host"] %>
      port: <%= ENV["lando_catalog_solr_conn_port"] %>
      collection: "catalog"

  dpul:
    solr:
      host: <%= ENV["lando_dpul_solr_conn_host"] %>
      port: <%= ENV["lando_dpul_solr_conn_port"] %>
      collection: "dpul"

  findingaids:
    solr:
      host: <%= ENV["lando_findingaids_solr_conn_host"] %>
      port: <%= ENV["lando_findingaids_solr_conn_port"] %>
      collection: "findingaids"
  
  pulmap:
    solr:
      host: <%= ENV["lando_pulmap_solr_conn_host"] %>
      port: <%= ENV["lando_pulmap_solr_conn_port"] %> 
      collection: "pulmap"

staging:
  <<: *default
  catalog:
    solr:
      host: "lib-solr8-staging.princeton.edu"
      port: 8983
      collection: "catalog-alma-staging"
  dpul:
    solr:
      host: "lib-solr8-staging.princeton.edu"
      port: 8983
      collection: "dpul-staging"
  findingaids:
    solr:
      host: "lib-solr8-staging.princeton.edu"
      port: 8983
      collection: "pulfalight-staging"

test:
  <<: *default
  summon:
    access_id: 'princeton'
    api_host: 'api.summon.serialssolutions.com'
    api_path: '/2.0.0/search'
    secret_key: 'ed2ee2e0-65c1-11de-8a39-0800200c9a66'

production:
  <<: *default
