default: &default
  catalog:
    subdomain: catalog
    solr:
      host: "lib-solr8-prod.princeton.edu"
      port: 8983
      collection: "catalog-alma-production"
  dpul:
    subdomain: dpul
    solr:
      host: "lib-solr8-prod.princeton.edu"
      port: 8983
      collection: "dpul-production"
  findingaids:
    subdomain: findingaids
    solr:
      host: "lib-solr8-prod.princeton.edu"
      port: 8983
      collection: "pulfalight-production"
  libanswers:
    client_id: <%= ENV['LIBANSWERS_CLIENT_ID'] || 'ABC' %>
    client_secret: <%= ENV['LIBANSWERS_CLIENT_SECRET'] || '12345' %>
  libguides:
    client_id: <%= ENV['LIBGUIDES_CLIENT_ID'] || 'ABC' %>
    client_secret: <%= ENV['LIBGUIDES_CLIENT_SECRET'] || '12345' %>
  library_website:
    host: "library.psb-prod.princeton.edu"
    path: "/ps-library/search/results"
  pulmap:
    subdomain: pulmap
    solr: 
      host: "lib-solr8-prod.princeton.edu"
      port: 8983
      collection: "pulmap"
  summon:
    access_id: 'princeton'
    secret_key: <%= ENV['SUMMON_SECRET_KEY'] || 'summon-secret-key' %>
development:
  <<: *default
  catalog:
    solr:
      host: <%= ENV["lando_catalog_solr_conn_host"] %>
      port: <%= ENV["lando_catalog_solr_conn_port"] %>
      collection: "catalog"

  dpul:
    solr:
      host: <%= ENV["lando_dpul_solr_conn_host"] %>
      port: <%= ENV["lando_dpul_solr_conn_port"] %>
      collection: "dpul"

  findingaids:
    solr:
      host: <%= ENV["lando_findingaids_solr_conn_host"] %>
      port: <%= ENV["lando_findingaids_solr_conn_port"] %>
      collection: "findingaids"
  
  pulmap:
    solr:
      host: <%= ENV["lando_pulmap_solr_conn_host"] %>
      port: <%= ENV["lando_pulmap_solr_conn_port"] %> 
      collection: "pulmap"

staging:
  <<: *default
  catalog:
    subdomain: catalog-staging
    solr:
      host: "lib-solr8-staging.princeton.edu"
      port: 8983
      collection: "catalog-staging"
  dpul:
    subdomain: dpul-staging
    solr:
      host: "lib-solr8-staging.princeton.edu"
      port: 8983
      collection: "dpul-staging"
  findingaids:
    subdomain: findingaids-staging
    solr:
      host: "lib-solr8d-staging.princeton.edu"
      port: 8983
      collection: "pulfalight-staging"
  library_website:
    host: "library.psb-test.princeton.edu"
    path: "/ps-library/search/results"

test:
  <<: *default
  libanswers:
    client_id: <%= 'ABC' %>
    client_secret: <%= '12345' %>
  libguides:
    client_id: <%= 'ABC' %>
    client_secret: <%= '12345' %>

production:
  <<: *default
