default: &default
  catalog:
    subdomain: catalog
    solr:
      host: <%= ENV['CATALOG_SOLR_HOST'] || "lib-solr8-prod.princeton.edu" %>
      port: 8983
      collection: <%= ENV['CATALOG_SOLR_COLLECTION'] || "catalog-alma-production" %>
  dpul:
    subdomain: dpul
    solr:
      host: <%= ENV['DPUL_SOLR_HOST'] || "lib-solr8-prod.princeton.edu" %>
      port: 8983
      collection: <%= ENV['DPUL_SOLR_COLLECTION'] || "dpul-production" %>
  findingaids:
    subdomain: findingaids
    solr:
      host: <%= ENV['FINDINGAIDS_SOLR_HOST'] || "lib-solr8-prod.princeton.edu" %>
      port: 8983
      collection: <%= ENV['FINDINGAIDS_SOLR_COLLECTION'] || "pulfalight-production" %>
  libanswers:
    client_id: <%= ENV['LIBANSWERS_CLIENT_ID'] || 'ABC' %>
    client_secret: <%= ENV['LIBANSWERS_CLIENT_SECRET'] || '12345' %>
  libguides:
    client_id: <%= ENV['LIBGUIDES_CLIENT_ID'] || 'ABC' %>
    client_secret: <%= ENV['LIBGUIDES_CLIENT_SECRET'] || '12345' %>
  library_website:
    temporary_host: "library.psb-prod.princeton.edu"
    host: "library.princeton.edu"
    path: "/ps-library/search/results"
  pulmap:
    subdomain: maps
    solr: 
      host: <%= ENV['PULMAP_SOLR_HOST'] || "lib-solr8-prod.princeton.edu" %>
      port: 8983
      collection: <%= ENV['PULMAP_SOLR_COLLECTION'] || "pulmap" %>
  summon:
    access_id: 'princeton'
    secret_key: <%= ENV['SUMMON_SECRET_KEY'] || 'summon-secret-key' %>
development:
  <<: *default
  catalog:
    subdomain: catalog-staging
    solr:
      host: <%= ENV["lando_catalog_solr_conn_host"] %>
      port: <%= ENV["lando_catalog_solr_conn_port"] %>
      collection: "catalog"

  dpul:
    subdomain: dpul-staging
    solr:
      host: <%= ENV["lando_dpul_solr_conn_host"] %>
      port: <%= ENV["lando_dpul_solr_conn_port"] %>
      collection: "dpul"

  findingaids:
    subdomain: findingaids-staging
    solr:
      host: <%= ENV["lando_findingaids_solr_conn_host"] %>
      port: <%= ENV["lando_findingaids_solr_conn_port"] %>
      collection: "findingaids"
  
  pulmap:
    subdomain: maps
    solr:
      host: <%= ENV["lando_pulmap_solr_conn_host"] %>
      port: <%= ENV["lando_pulmap_solr_conn_port"] %> 
      collection: "pulmap"

staging:
  <<: *default
  catalog:
    subdomain: catalog-staging
    solr:
      host: <%= ENV['CATALOG_SOLR_HOST'] || "lib-solr8d-staging.princeton.edu" %>
      port: 8983
      collection: <%= ENV['CATALOG_SOLR_COLLECTION'] || "catalog-staging" %>
  dpul:
    subdomain: dpul-staging
    solr:
      host: <%= ENV['DPUL_SOLR_HOST'] || "lib-solr8d-staging.princeton.edu" %>
      port: 8983
      collection: <%= ENV['DPUL_SOLR_COLLECTION'] || "dpul-staging" %>
  findingaids:
    subdomain: findingaids-staging
    solr:
      host: <%= ENV['FINDINGAIDS_SOLR_HOST'] || "lib-solr8d-staging.princeton.edu" %>
      port: 8983
      collection: <%= ENV['FINDINGAIDS_SOLR_COLLECTION'] || "pulfalight-staging" %>
  library_website:
    temporary_host: "library.psb-test.princeton.edu"
    host: "library.psb-test.princeton.edu"
    path: "/ps-library/search/results"

test:
  <<: *default
  libanswers:
    client_id: <%= 'ABC' %>
    client_secret: <%= '12345' %>
  libguides:
    client_id: <%= 'ABC' %>
    client_secret: <%= '12345' %>

production:
  <<: *default
